//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiHoYoStarter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenshinPath {
            get {
                return ((string)(this["GenshinPath"]));
            }
            set {
                this["GenshinPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenshinCloudPath {
            get {
                return ((string)(this["GenshinCloudPath"]));
            }
            set {
                this["GenshinCloudPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StarRailPath {
            get {
                return ((string)(this["StarRailPath"]));
            }
            set {
                this["StarRailPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayGenshinEnabled {
            get {
                return ((bool)(this["DisplayGenshinEnabled"]));
            }
            set {
                this["DisplayGenshinEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayGenshinCloudEnabled {
            get {
                return ((bool)(this["DisplayGenshinCloudEnabled"]));
            }
            set {
                this["DisplayGenshinCloudEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayStarRailEnabled {
            get {
                return ((bool)(this["DisplayStarRailEnabled"]));
            }
            set {
                this["DisplayStarRailEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenshinStartParam {
            get {
                return ((string)(this["GenshinStartParam"]));
            }
            set {
                this["GenshinStartParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StarRailStartParam {
            get {
                return ((string)(this["StarRailStartParam"]));
            }
            set {
                this["StarRailStartParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HonkaiImpact3Path {
            get {
                return ((string)(this["HonkaiImpact3Path"]));
            }
            set {
                this["HonkaiImpact3Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HonkaiImpact3StartParam {
            get {
                return ((string)(this["HonkaiImpact3StartParam"]));
            }
            set {
                this["HonkaiImpact3StartParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayHonkaiImpact3Enabled {
            get {
                return ((bool)(this["DisplayHonkaiImpact3Enabled"]));
            }
            set {
                this["DisplayHonkaiImpact3Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenshinAutoStartEnabled {
            get {
                return ((bool)(this["GenshinAutoStartEnabled"]));
            }
            set {
                this["GenshinAutoStartEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StarRailAutoStartEnabled {
            get {
                return ((bool)(this["StarRailAutoStartEnabled"]));
            }
            set {
                this["StarRailAutoStartEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HonkaiImpact3AutoStartEnabled {
            get {
                return ((bool)(this["HonkaiImpact3AutoStartEnabled"]));
            }
            set {
                this["HonkaiImpact3AutoStartEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenshinCloudAutoStartEnabled {
            get {
                return ((bool)(this["GenshinCloudAutoStartEnabled"]));
            }
            set {
                this["GenshinCloudAutoStartEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GenshinServerIndex {
            get {
                return ((int)(this["GenshinServerIndex"]));
            }
            set {
                this["GenshinServerIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StarRailServerIndex {
            get {
                return ((int)(this["StarRailServerIndex"]));
            }
            set {
                this["StarRailServerIndex"] = value;
            }
        }
    }
}
